# Makefile for a cc3 project


# C files to compile
CSOURCES=main.c relive.c parser.c

# header files
INCLUDES=relive.h parser.h

# header files
LIBS=cc3-ilp

# the name of this project
PROJECT=relive


# the makefile is useless without the next line!
include ../../include/common.mk
