# Makefile for a cc3 project


# C files to compile
CSOURCES=parser.c relive.c main.c

# header files
INCLUDES=parser.h relive.h

# header files
LIBS=cc3-ilp jpeg-6b

# the name of this project
PROJECT=relive


# the makefile is useless without the next line!
include ../../include/common.mk
