# Makefile for a cc3 project


# C files to compile
CSOURCES=face.c face_test.c

# header files
INCLUDES=vj.h

# header files
LIBS=cc3-ilp

# the name of this project
PROJECT=viola-jones


# the makefile is useless without the next line!
include ../../include/common.mk
